---
title: "R Notebook"
output:
  html_document: default
  html_notebook: default
  pdf_document: default
---

```{r setup, include=FALSE, error=TRUE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, comment = NA, error = TRUE)
```

```{r}
plotSegment <- function(P1, P2, ...) {
  segments(P1[1], P1[2], P2[1], P2[2], ...)
}
```

```{r}
A <- c(2,4) 
B <- c(4,-2) 
C <- c(8,10) 

slope <- ( C[2]- A[2])/(C[1]-A[1])  #rise/run 

# find the D point on the line AB
D <- c(B[1], (B[1]-A[1]) * slope + A[2])  # find D 

my.data <- rbind(A,B,C,D)

colnames(my.data) <- c("X","Y") 
my.data    #show it 

plot(my.data, type="n")   #graph it without the points 
text(my.data, rownames(my.data))  #put the points in 
segments(A[1], A[2], C[1], C[2])   #draw the line segments 
segments(B[1], B[2], D[1], D[2]) 

plotSegment(A, B, col = 'green')

points(A, pch = 20, alpha=0.5, col = "orange")
```




## How to drop a perpendicular line from each point in a scatterplot to an (Eigen) vector?

http://stackoverflow.com/q/30398908

```{r}

library(ggplot2)

perp.segment.coord <- function(x0, y0, a=0,b=1){
 #finds endpoint for a perpendicular segment from the point (x0,y0) to the line
 # defined by lm.mod as y=a+b*x
  x1 <- (x0+b*y0-a*b)/(1+b^2)
  y1 <- a + b*x1
  list(x0=x0, y0=y0, x1=x1, y1=y1)
}



Person1 <- c(-3,1,1,-3,0,-1,-1,0,-1,-1,3,4,5,-2,1,2,-2,-1,1,-2,1,-3,4,-6,1,-3,-4,3,3,-5,0,3,0,-3,1,-2,-1,0,-3,3,-4,-4,-7,-5,-2,-2,-1,1,1,2,0,0,2,-2,4,2,1,2,2,7,0,3,2,5,2,6,0,4,0,-2,-1,2,0,-1,-2,-4,-1)

Person2 <- c(-4,-3,4,-5,-1,-1,-2,2,1,0,3,2,3,-4,2,-1,2,-1,4,-2,6,-2,-1,-2,-1,-1,-3,5,2,-1,3,3,1,-3,1,3,-3,2,-2,4,-4,-6,-4,-7,0,-3,1,-2,0,2,-5,2,-2,-1,4,1,1,0,1,5,1,0,1,1,0,2,0,7,-2,3,-1,-2,-3,0,0,0,0)

df <- data.frame(cbind(Person1, Person2))

g <- ggplot(data = df, mapping = aes(x = Person1, y = Person2))
g <- g + geom_point(alpha = 1/3)  # alpha b/c of overplotting
g <- g + geom_smooth(method = "lm")  # just for comparsion
g <- g + coord_fixed()  # otherwise, the angles of vectors are off

corre <- cor(x = df$Person1, y = df$Person2, method = "spearman")  # calculate correlation, must be spearman b/c of measurement
matrix <- matrix(c(1, corre, corre, 1), nrow = 2)  # make this into a matrix
eigen <- eigen(matrix)  # calculate eigenvectors and values
eigen$vectors.scaled <- eigen$vectors %*% diag(sqrt(eigen$values))  
  # scale eigenvectors to length = square-root
  # as per http://stats.stackexchange.com/questions/9898/how-to-plot-an-ellipse-from-eigenvalues-and-eigenvectors-in-r


g <- g + stat_ellipse(type = "norm")
g <- g + stat_ellipse(type = "t")

ss <- perp.segment.coord(df$Person1, df$Person2, 0, eigen$vectors.scaled[1,1])

g + geom_segment(data=as.data.frame(ss), aes(x = x0, y = y0, xend = x1, yend = y1), colour = "blue")
```



